# Generated by Django 4.1.7 on 2023-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_bairro_comentario_cep_comentario_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
