# Generated by Django 4.1.7 on 2023-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='bairro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='cidade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='complemento',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='rua',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cidadao',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
